config/routes.rb
Rails.application.routes.draw do
  mount Shoppe::Engine => "/shoppe"
  
  get 'products/index'
  get "product/:permalink", to: "products#show", as: "product"
  post "product/:permalink", to: "products#buy", as: "buy"

  get "basket", to: "orders#show"
  delete "basket", to: "orders#destroy"

  match "checkout", to: "orders#checkout", as: "checkout", via: [:get, :patch]
  match "checkout/pay", to: "orders#payment", as: "checkout_payment", via: [:get, :post]
  match "checkout/confirm", to: "orders#confirmation", as: "checkout_confirmation", via: [:get, :post]
  get "checkout/paypal", to: "orders#paypal"

  root 'products#index'

  devise_for :users

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_order
    @current_order ||= begin
      if has_order?
        @current_order
      else
        order = Shoppe::Order.create(:ip_address => request.ip)
        session[:order_id] = order.id
        order
      end
    end
  end

  def has_order?
    !!(
      session[:order_id] &&
      @current_order = Shoppe::Order.includes(:order_items => :ordered_item).find_by_id(session[:order_id])
    )
  end

  helper_method :current_order, :has_order?
  
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	before_filter(only: [:paypal, :payment]) { Shoppe::Paypal.setup_paypal }

	def destroy
	  current_order.destroy
	  session[:order_id] = nil
	  redirect_to root_path, :notice => "Eliminado."
	end

	def checkout
	  @order = Shoppe::Order.find(current_order.id)
	  if request.patch?
	    if @order.proceed_to_confirm(params[:order].permit(:first_name, :last_name, :billing_address1, :billing_address2, :billing_address3, :billing_address4, :billing_country_id, :billing_postcode, :email_address, :phone_number))
	      redirect_to checkout_payment_path
	    end
	  end
	end

	def payment
	  if request.post?
	    redirect_to checkout_confirmation_path
	  end
	end

	def confirmation
	  if request.post?
	    current_order.confirm!
	    session[:order_id] = nil
	    redirect_to root_path, :notice => "Order has been placed successfully!"
	  end
	end

	def paypal
	  @order = Shoppe::Order.find(session[:current_order_id])
	  url = @order.redirect_to_paypal(checkout_payment_url(success: true), checkout_payment_url(success: false))
	  redirect_to url

	  	if params[:success] == "true" && params[:PayerID].present?
  			@order.accept_paypal_payment(params[:paymentId], params[:token], params[:PayerID])
		end
	end

	

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
#before_filter :authenticate_user!
  def index
    @products = Shoppe::Product.root.ordered.includes(:product_categories, :variants)
    @products = @products.group_by(&:product_category)
  end

  def show
    @product = Shoppe::Product.root.find_by_permalink(params[:permalink])
  end

  def buy
	@product = Shoppe::Product.root.find_by_permalink!(params[:permalink])
	current_order.order_items.add_item(@product, 1)
	redirect_to product_path(@product.permalink), :notice => "Producto agregado"
  end

end

app/controllers/test_controller.rb
class TestController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="clearfix">
    <div class="row">
      <div class="medium-6 large-6 columns">
        <div class="large-8 columns">
            <figure>
              <%= image_tag("footer.png", :alt=> "logo") %>
            </figure>
          <h5 class="cc">&copy; 2015, Bisutería Jaramillo S.A de C.V.</h5>
          <h6>Justo Sierra 41 Col. Centro, Distrito Federal, México.</h6>

        </div>
      </div>
      <div class="medium-6 large-6 columns text-center">
        <p class="feedback">Síguenos en nuestras redes sociales.</p>
        <ul class="social">
          <li><a href="https://www.facebook.com/elcastillodelafantasiamx"><span class="fa fa-facebook cuadro"> </span></a></li>
          <li><a href="https://twitter.com/@ElCastillodelaF"><span class="fa fa-twitter cuadro"> </span></a></li>
          <li><a href="https://instagram.com/ElCastillomx"><span class="fa fa-instagram cuadro"> </span></a></li>
          <li><a href="https://es.pinterest.com/ElCastillomx"><span class="fa fa-pinterest cuadro"> </span></a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="small-12 large-12 columns">
      <ul class="legals">
        <li><a href="">Términos y condiciones.</a></li>
        <li><a href="">Aviso Legal.</a></li>
      </ul>
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar" role="navigation">
    <div class="row" data-equalizer>
      <div class="small-12 medium-8 large-4 columns">
        <figure>
          <%= link_to image_tag("logo.png", :alt => "logo"), root_path %>
        </figure>
      </div>
      <div class="large-8 columns">
        <div class="row">
          <div class="animated slideInDown small-12 columns">
            <nav>
              <ul class="legals1">
                <% if user_signed_in? %>
                  <li><%= link_to 'Editar cuenta', edit_user_registration_path, :class => 'navbar-link' %></li> 
                  <li><%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>    
                  <li><%= image_tag "min.png", :alt => "Mi cesta" %> <span class="label radius"><%= pluralize current_order.total_items, 'item' %></span></li>                 
                <% else %>                
                  <li><%= link_to "Regístrate", new_user_registration_path, :class => 'navbar-link'  %></li>
                  <li><%= link_to "Inicia sesión", new_user_session_path, :class => 'navbar-link'  %></li>                
                <% end %>
              </ul>              
            </nav>
          </div>
        </div>
      </div>
    </div>
</nav> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "El Castillo de la Fantasía | Joyería de Fantasía Fina, Pelucas y Postizos, Extensiones de Cabello y todo lo relacionado al Cabello." %></title>
    <link href='http://elcastillodelafantasia.com.mx/css/splikux.css' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Yanone+Kaffeesatz' rel='stylesheet' type='text/css'>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= render :partial => "layouts/navbar" %>

  <%= yield %>

    <%= render :partial => "layouts/footer" %>

  </body>
</html>

app/views/orders/_items.html.erb
<section>
  <div class="row">
    <div class="large-12 columns">
      <table width='100%' border='1'>
        <thead>
          <tr>
            <td>Cantidad</td>
            <td>Producto</td>
            <td>Sub-Total</td>
            <td>IVA</td>
            <td>Total</td>
          </tr>
        </thead>
        <tbody>
          <% order.order_items.each do |item| %>
          <tr>
            <td><%= item.quantity %></td>
            <td><%= item.ordered_item.full_name %></td>
            <td><%= number_to_currency item.sub_total %></td>
            <td><%= number_to_currency item.tax_amount %></td>
            <td><%= number_to_currency item.total %></td>
          </tr>
          <% end %>

          <% if order.delivery_service %>
          <tr>
            <td></td>
            <td><%= order.delivery_service.name %></td>
            <td><%= number_to_currency order.delivery_price %></td>
            <td><%= number_to_currency order.delivery_tax_amount %></td>
            <td><%= number_to_currency order.delivery_price + order.delivery_tax_amount %></td>
          </tr>
          <% end %>

        </tbody>
        <tfoot>
          <tr>
            <td colspan='4'>Sub-Total</td>
            <td><%= number_to_currency order.total_before_tax %></td>
          </tr>
          <tr>
            <td colspan='4'>IVA 16%</td>
            <td><%= number_to_currency order.tax %></td>
          </tr>
          <tr>
            <td colspan='4'>Total</td>
            <td><%= number_to_currency order.total %></td>
          </tr>
        </tfoot>
      </table>
    </div>
  </div>
</section>

app/views/orders/checkout.html.erb
<section>
	<div class="row">
		<div class="large-12 columns">
			<h3>Tu cuenta</h3>
			<%= render 'items', :order => @order %>

			<%= form_for @order, :url => checkout_path do |f| %>
			  <dl>
			    <dt><%= f.label :first_name, 'Name' %></dt>
			    <dd><%= f.text_field :first_name %> <%= f.text_field :last_name %></dd>

			    <dt><%= f.label :billing_address1, 'Address' %></dt>
			    <dd><%= f.text_field :billing_address1 %></dd>
			    <dd><%= f.text_field :billing_address2 %></dd>
			    <dd><%= f.text_field :billing_address3 %></dd>
			    <dd><%= f.text_field :billing_address4 %></dd>
			    <dt><%= f.label :billing_postcode, 'Post code' %></dt>
			    <dd><%= f.text_field :billing_postcode %></dd>
			    <dd><%= f.collection_select :billing_country_id, Shoppe::Country.ordered, :id, :name, :include_blank => true %></dd>

			    <dt><%= f.label :email_address %></dt>
			    <dd><%= f.text_field :email_address %></dd>

			    <dt><%= f.label :phone_number %></dt>
			    <dd><%= f.text_field :phone_number %></dd>

			    <dd><%= f.submit 'Continue' %></dd>
			  </dl>
			<% end %>
		</div>
	</div>
</section>

app/views/orders/confirmation.html.erb
<section>
	<div class="row">
		<div class="large-12 columns">
			<h2>Realizar pedido</h2>
			<%= render 'items', :order => current_order %>
			<%= button_to "Pedir" %>			
		</div>
	</div>
</section>

app/views/orders/payment.html.erb
<section>
	<div class="row">
		<div class="large-12 columns">
			<%= shoppe_stripe_javascript %>

			<h2>Make your payment</h2>

			<% if params[:success] == "true" && params[:PayerID].present? %>

			  <p>Payment will be processed by PayPal</p>
			  <%= link_to "Continue", checkout_confirmation_path %>

			<% else %>

			  <%= form_tag nil, class: "stripeForm" do %>
			    <%= hidden_field_tag "stripe_token", nil, "data-stripe" => "token" %>
			    <dl>
			      <dt><%= label_tag 'card_number' %></dt>
			      <dd><%= text_field_tag 'card_number', nil, name: nil, "data-stripe" => "number" %></dd>
			      <dt><%= label_tag 'expiry_month' %></dt>
			      <dd><%= text_field_tag 'expiry_month', nil, name: nil, "data-stripe" => "exp_month" %></dd>
			      <dt><%= label_tag 'expiry_year' %></dt>
			      <dd><%= text_field_tag 'expiry_year', nil, name: nil, "data-stripe" => "exp_year" %></dd>
			      <dt><%= label_tag 'security_code' %></dt>
			      <dd><%= text_field_tag 'security_code', nil, name: nil, "data-stripe" => "cvc" %></dd>
			      <dd><%= submit_tag "Continue" %></dd>
			    </dl>
			  <% end %>

			  <hr>

			  <%= link_to "Pay with PayPal", checkout_paypal_path %>

			<% end %>
		</div>
	</div>
</section>

app/views/orders/show.html.erb
<section>
	<div class="row">
		<div class="large-12 columns">
			<h3>Tu cuenta</h3>
			<%= render 'items', :order => current_order %>
		</div>
	</div>
	<p><%= link_to 'Vaciar', basket_path, :method => :delete %></p>
</section>

app/views/products/index.html.erb
<% if user_signed_in? %>
  <section>
    <div class="row">
      <div class="large-8 columns" data-equalizer>
        <% @products.each do |category, products| %>
          <h3><%= category.name %></h3>
          <ul>
            <% products.each do |product| %>
              <div class="row" data-equalizer>
                  <div class="large-4 panel callout radius columns" data-equalizer-watch>
                    <li class="contenedor">
                      <img src="product.default_image">
                      <h4><%= link_to product.name, product_path(product.permalink) %></h4>
                      <p><%= product.short_description %></p>
                      <p><b>Precio:</b> <%= number_to_currency product.price %></p>               
                    </li>
                  </div>
              </div>
            <% end %>
          </ul>
        <% end %>
      </div>
      <div class="large-4 columns text-center" data equalizer>
        <div class="large-12">
          <h2>Tu sucursal mas cercana es: <i class="fa fa-map-marker"></i> <strong>Justo Sierra</strong>
            <% if notice %>
              <%= notice %>
            <% end %>
            <% if alert %>
              <%= alert %>
            <% end %>
          </h2>
        </div>
        <div class="large-12 panel">
          <h2><%= gravatar_image_tag(current_user.email, :alt=> current_user.email, :class=> 'circle') %> <%= current_user.email %></h2>
          <h2>Mi cuenta va: <i class="fa fa-shopping-cart"></i> <%= number_to_currency current_order.total_before_tax %></h2>
          <%= link_to "Ver mi canasta", basket_path, :class => 'button tiny expand radius' %>
          <%= link_to "Pagar", checkout_path, :class => 'button tiny expand radius' %>              
        </div>         
      </div>
    </div>
  </section>
<% else %>
  <header class="animated fadeIn">
    <div class="row">
      <div class="large-6 columns cuadro">
        <h1 class="cuadro"><%= t(".brand") %></h1>
          <p> <%= t(".copy") %> </p>
      </div>
      <div class="small-12 large-12 text-center columns">
        <div class="logo">
          <figure>
            <%= image_tag "bag.png", :alt => t(".brand") %>
          </figure>
        </div>
        <div class="large-12 columns cuadro1">
          <h6 class="cuadro">Recibe en tu correo las ofertas y promociones que tenemos, suscríbete a nuestro boletín.</h6>
          <a href="" data-reveal-id="myModal1" class="button tiny"><i class="fa fa-newspaper-o"></i> ¡Suscribirme ahora!</a>
        </div>
      </div>
    </div>
  </header>
  <%= render :partial => "test/contact" %>
<% end %>

app/views/products/show.html.erb
<section>
	<div class="row">
		<div class="large-12 columns">
			<h3><%= @product.name %></h3>

			<% if @product.default_image %>
			  <%= image_tag @product.default_image.path, :width => '200px', :style => "float:right" %>
			<% end %>

			<p><%= @product.short_description %></p>
			<p>
			  <b><%= number_to_currency @product.price %></b>
			  <%= link_to "Agregar", product_path(@product.permalink), :method => :post %>
			</p>

			<%= simple_format @product.description %>

			<%= link_to "Regresar a la lista", root_path, :class => 'button tiny radius' %>
		</div>
	</div>
</section>
<section>
	<div class="row">
		<div class="large-12 columns">
			<h3>Productos relacionados.</h3>
		</div>
	</div>
</section>